#!/bin/sh
# husky
cd .
[ -f package.json ] && cat package.json | grep -q '"prepush"\s*:'
[ $? -ne 0 ] && exit 0
export NVM_DIR="/home/xander/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
command -v nvm >/dev/null 2>&1 && [ -f .nvmrc ] && nvm use
command -v npm >/dev/null 2>&1 || { echo >&2 "husky - can't find npm in PATH. Skipping prepush script in package.json"; exit 0; }
export GIT_PARAMS="$*"
npm run prepush
if [ $? -ne 0 ]; then
  echo
  echo "husky - pre-push hook failed (add --no-verify to bypass)"
  echo
  exit 1
fi
